

server:
  port: 9010

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    root: INFO
#    com.example.vue3study.api: DEBUG
  pattern:
    console: "%-20(%cyan(%date{HH:mm:ss.SSS}) [%thread] [tid=%X{tid}]) %highlight(%-5level) %magenta(%marker|%logger{36}): %msg%n%rEx"


